services:
  db:
    platform: linux/amd64
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: findyourmp_development
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    command: ["--sql-mode=", "--default-authentication-plugin=mysql_native_password"]

  app:
    platform: linux/amd64
    build: .
    working_dir: /app
    environment:
      RAILS_ENV: development
      USE_DOCKER_DB: "true"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  dbdata:
