development:
  adapter: <%= ENV['USE_DOCKER_DB'] ? 'mysql' : 'mysql2' %>
  database: findyourmp_development
  username: root
  password: <%= ENV['USE_DOCKER_DB'] ? 'root' : '' %>
<% if ENV['USE_DOCKER_DB'] %>
  host: db
  port: 3306
<% else %>
  socket: /tmp/mysql.sock
<% end %>
test:
  adapter: <%= ENV['USE_DOCKER_DB'] ? 'mysql' : 'mysql2' %>
  database: findyourmp_test
  username: root
  password: <%= ENV['USE_DOCKER_DB'] ? 'root' : '' %>
<% if ENV['USE_DOCKER_DB'] %>
  host: db
  port: 3306
<% else %>
  socket: /tmp/mysql.sock
<% end %>
    
    
production:
  adapter: <%= ENV['USE_DOCKER_DB'] ? 'mysql' : 'mysql2' %>
  database: findyourmp_production
  username: root
  password: <%= ENV['USE_DOCKER_DB'] ? 'root' : '' %>
<% if ENV['USE_DOCKER_DB'] %>
  host: db
  port: 3306
<% else %>
  socket: /tmp/mysql.sock
<% end %>
